- name: show return value of command module
  hosts: vagrant1
  tasks:
    - name: capture output of whoami command
      command: whoami
      register: login
#    - debug: var=login
    - debug: msg="Logged as {{ login.stdout }}"
