- name: setup php
  hosts: webserver
  become: True
  tasks:
    - name: install epel-release
      yum:
        name: epel-release
        state: latest
    - name: install yum-utils
      yum:
        name: yum-utils
        state: present
    - name: install remi-release-7
      yum:
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present
    - name: enable remi-php74
      shell: yum-config-manager --enable remi-php74
    - name: install php packages
      yum:
        name:
          - php
          - php-bcmath
          - php-cli
          - php-common
          - php-devel
          - php-gd
          - php-imap
          - php-intl
          - php-json
          - php-ldap
          - php-lz4
          - php-mbstring
          - php-mysqlnd
          - php-soap
          - php-intl
          - php-opcache
          - php-xml
          - php-pdo
        state: present

- name: setup mysql
  hosts: webserver
  become: True
  tasks:
    - name: Install MySQL 5.7 repo
      yum:  # параметры можно передавать в yaml
        name: http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm
        state: present
    - name: Install MySQL 5.7
      yum:
        name:
          - mysql-community-server
          - mysql-community-client
    - name: Start the MySQL service
      service: >  # так можно разбить строку с параметрами
        name=mysqld
        state=started
        enabled=true

