Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "vagrant" do |vagrant1|
    vagrant1.vm.box = "centos/7"
    vagrant1.vm.network "forwarded_port", guest: 80, host: 8080
    vagrant1.vm.network "forwarded_port", guest: 443, host: 8443
  end

end
